model:
  name: yolov8n_256
  uc: od_coco
  model_path: ./saved_model
  input_shape: [256, 256, 3]
quantization:
  fake: False
  quantization_type: per_channel
  quantization_input_type: uint8
  quantization_output_type: int8
  calib_dataset_path: ./calibration_dataset
  export_path: ./quantized_models
  max_calib_images: 200  # Maximum number of calibration images to use (prevents memory issues)
pre_processing:
  rescaling: {scale: 255, offset: 0}
